spring.datasource.url=jdbc:mysql://localhost:3306/penetrate?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ykycx9552
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.web.resources.static-locations=classpath:/templates/
server.tomcat.connection-timeout=3600000
server.tomcat.keep-alive-timeout=3600000
spring.jackson.serialization.write-dates-as-timestamps=false


# Server
server.port=8080
# MSF
msf.path=/usr/bin/msfconsole

# Security
spring.security.user.name=admin
spring.security.user.password=admin